In [68]:
import numpy as np
import sys

np.random.seed(0)

def set_lowVal_zero(X):
    low_values_indices = abs(X) < 9e-15   # where values are low
    X[low_values_indices] = 0             # all low values set to 0
    return X

def householder(x, i):
    alpha = -np.sign(x[i])*np.linalg.norm(x)
    print(alpha)
    e = np.zeros(len(x))
    e[i] = 1.0
    v = x - alpha*e
    w = v / np.linalg.norm(v)
    P = np.eye(len(x)) - 2 * np.outer(w, w.T)
    return P
        
A = np.random.randint(10, size=(4,4))
J = A.copy()

for i in range(3):
    
    h = np.zeros(len(A[:,i]))
    h[i:] = J[i: ,i]
    P = householder(h, i)
    J = P@J   
    
    h = np.zeros(len(J[i, :]))
    h[i+1:] = J[i,i+1:]
    Q = householder(h, i+1)
    J = J@Q
    J = set_lowVal_zero(J)
#    with np.printoptions(precision=4, suppress=True, formatter={'float': '{:0.4f}'.format}, linewidth=100):
#        print(J)
    print(J)
    print(' ')



print(J)
print(J[2,2])
firstMat = np.array([[J[2,2]**2 + J[1,2]**2, J[2,2]*J[2,3]],
                     [J[2,2]*J[2,3], J[3,3]**2 + J[2,3]**2]
                    ])
print(firstMat)

eigenvalues, eigenvectors = np.linalg.eig(firstMat)

-11.916375287812984
15.402807499713793
[[-11.91637529  15.4028075    0.           0.        ]
 [  0.          -3.05418634  -1.59670191  -2.604903  ]
 [  0.          -6.60416932   4.3829604    1.3546433 ]
 [  0.          -1.21313588  -3.42253984  -1.11559849]]
 
7.376639155159193
2.7004829255852942
[[-11.91637529  15.4028075    0.           0.        ]
 [  0.           7.37663916   2.70048293   0.        ]
 [  0.           0.          -3.62848831   3.10168527]
 [  0.           0.           3.5355698   -0.87147871]]
 
5.066180139223167
2.8296669604973186
[[-11.91637529  15.4028075    0.           0.        ]
 [  0.           7.37663916   2.70048293   0.        ]
 [  0.           0.           5.06618014   2.82966696]
 [  0.           0.           0.          -1.54042577]]
 
[[-11.91637529  15.4028075    0.           0.        ]
 [  0.           7.37663916   2.70048293   0.        ]
 [  0.           0.           5.06618014   2.82966696]
 [  0.           0.           0.          -1.54042577

In [71]:
B = J
print(B[1,2])
print(B)
def implicitQR(B):
    r = B.shape[0] - 1
    u = B[r,r]
    
    for i in range(0,r-1):
        if (i == 0):
            alpha = B[0,0]**2 - u**2
            beta = B[0,0]*B[0,1]
        else:
            alpha = B[i-1,i]
            beta = B[i-1,i+1]
        
        theta = np.arctan(beta/alpha)
        
        rot = np.array([[np.cos(theta), -np.sin(theta)],[np.sin(theta), np.cos(theta)]])
        C = B[0:r,i:i+2] * rot
        B[0:r, i:i+2] = C
        
        alpha = B[r,r]
        beta = B[i-1,i+1]
        
        theta = np.arctan(beta/alpha)
        
        C = np.array([[np.cos(theta), -np.sin(theta)],[np.sin(theta), np.cos(theta)]]) * B[i:i+2,0:r]
        B[i:i+2, 0:r] = C
        
        print(B)
        return B
        

    

i = 3
SorD = False

while i > 0:
    j = i - 1
    while SorD == False:
        if B[j,j+1] <  0.000001:
            SorD = True
        else:
            j = j - 1
    if (SorD == True) & (j == i - 1):
        i = i - 1
    else:
        B[j+1:i,j+1:i] = implicitQR(B[j+1:i,j+1:i])    

print(B)

2.700482925585294
[[-6.37933494 -0.          0.          0.        ]
 [-0.          3.94902399  2.70048293  0.        ]
 [ 0.          0.          5.06618014  2.82966696]
 [ 0.          0.          0.         -1.54042577]]
[[-6.37933494 -0.          0.          0.        ]
 [-0.                 nan         nan  0.        ]
 [ 0.                 nan         nan  2.82966696]
 [ 0.          0.          0.         -1.54042577]]
