In [1]:
import numpy as np
import sys
import math

np.random.seed(0)

def set_lowVal_zero(X):
    low_values_indices = abs(X) < 9e-15   # where values are low
    X[low_values_indices] = 0             # all low values set to 0
    return X

def householder(x, i):
    ''' Calculates the householder refelections '''
    alpha = -np.sign(x[i])*np.linalg.norm(x)
    print(alpha)
    e = np.zeros(len(x))
    e[i] = 1.0
    v = x - alpha*e
    w = v / np.linalg.norm(v)
    P = np.eye(len(x)) - 2 * np.outer(w, w.T)
    return P
        
A = np.array([
    [1, 2, 3, 4],
    [5, 0, 2, 6],
    [8, 5, 4, 8],
    [6, 9, 7, 9]], dtype=np.float64)

J = A.copy()

for i in range(3):
    
    h = np.zeros(len(A[:,i]))
    h[i:] = J[i: ,i]
    P = householder(h, i)
    J = P@J   
    
    h = np.zeros(len(J[i, :]))
    h[i+1:] = J[i,i+1:]
    Q = householder(h, i+1)
    J = J@Q
    J = set_lowVal_zero(J)
#    with np.printoptions(precision=4, suppress=True, formatter={'float': '{:0.4f}'.format}, linewidth=100):
#        print(J)
    print(J)
    print(' ')



print(J)

-11.224972160321824
17.792677288125166
[[-1.12249722e+01  1.77926773e+01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  4.01239124e+00  5.31683376e-02  3.10636169e+00]
 [ 0.00000000e+00  4.88569590e+00 -1.03723853e+00  1.16638119e-02]
 [ 0.00000000e+00 -2.88482125e+00 -2.49162148e-01 -3.05593553e+00]]
 
-6.949208701399207
-3.127526125869511
[[-11.22497216  17.79267729   0.           0.        ]
 [  0.          -6.9492087   -3.12752613   0.        ]
 [  0.           0.          -2.5398856   -1.30278291]
 [  0.           0.          -1.32968664  -0.65679899]]
 
2.866894739223447
-1.458810590966904
[[-11.22497216  17.79267729   0.           0.        ]
 [  0.          -6.9492087   -3.12752613   0.        ]
 [  0.           0.           2.86689474  -1.45881059]
 [  0.           0.           0.          -0.02235824]]
 
[[-11.22497216  17.79267729   0.           0.        ]
 [  0.          -6.9492087   -3.12752613   0.        ]
 [  0.           0.           2.86689474  -1.45881059]
 [  

In [26]:
A = J
A =B5
print(A)

[[ 2.18501534e+01  1.18802717e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  5.07864120e+00  7.21260121e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  2.26048432e+00 -8.58070371e-01]
 [ 0.00000000e+00  0.00000000e+00 -1.81631459e-02 -1.30380621e-02]]


In [27]:
def givens_4x4(a,b):
    out = np.empty((2, 2))
    r = np.sqrt(a**2 + b**2)
    c = a/r
    s = b/r
    out[0][0] = c
    out[1][1] = c
    out[0][1] = -s
    out[1][0] = s
    return out
t00 = A[0][0]**2
t33 = A[2][3]**2 + A[3][3]**2
t10 = A[0][1] * A[0][0]

G0 = givens_4x4((t00-t33),t10)
print(G0)

[[ 0.99852058 -0.05437501]
 [ 0.05437501  0.99852058]]


In [29]:
b1 = np.zeros((2,2))
e1 = np.eye(2)
G0_mat = np.block([[G0,b1],[b1,e1]])
print(G0_mat)

[[ 0.99852058 -0.05437501  0.          0.        ]
 [ 0.05437501  0.99852058  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]


In [30]:
B1 = A@G0_mat
print(B1)

[[ 2.18824270e+01 -1.83269805e-03  0.00000000e+00  0.00000000e+00]
 [ 2.76151159e-01  5.07112778e+00  7.21260121e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  2.26048432e+00 -8.58070371e-01]
 [ 0.00000000e+00  0.00000000e+00 -1.81631459e-02 -1.30380621e-02]]


In [31]:
G0_hat = givens_4x4(B1[0][0], B1[1][0])
G0_hat_mat = np.block([[G0_hat.T,b1],[b1,e1]])
B2 = G0_hat_mat@B1
print(B2)

[[ 2.18841694e+01  6.21588102e-02  9.10141091e-03  0.00000000e+00]
 [ 5.55111512e-17  5.07074715e+00  7.21202694e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  2.26048432e+00 -8.58070371e-01]
 [ 0.00000000e+00  0.00000000e+00 -1.81631459e-02 -1.30380621e-02]]


In [32]:
def make_zero(A):
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            if abs(A[i][j]) < 1.00e-8:
                A[i][j] = 0.00
    return A

B2 = make_zero(B2)
print(B2)

[[ 2.18841694e+01  6.21588102e-02  9.10141091e-03  0.00000000e+00]
 [ 0.00000000e+00  5.07074715e+00  7.21202694e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  2.26048432e+00 -8.58070371e-01]
 [ 0.00000000e+00  0.00000000e+00 -1.81631459e-02 -1.30380621e-02]]


In [33]:
G1 = givens_4x4(B2[0][1],B2[0][2])
G1_mat = np.eye(4)
G1_mat[1:3, 1:3] = G1
print(G1_mat)

[[ 1.          0.          0.          0.        ]
 [ 0.          0.98944966 -0.1448771   0.        ]
 [ 0.          0.1448771   0.98944966  0.        ]
 [ 0.          0.          0.          1.        ]]


In [34]:
B3 = B2@G1_mat
B3 = make_zero(B3)
print(B3)

[[ 2.18841694e+01  6.28215995e-02  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  5.12173478e+00 -2.10413619e-02  0.00000000e+00]
 [ 0.00000000e+00  3.27492405e-01  2.23663544e+00 -8.58070371e-01]
 [ 0.00000000e+00 -2.63142383e-03 -1.79715185e-02 -1.30380621e-02]]


In [35]:
G2_hat = givens_4x4(B3[1][1], B3[2][1])
G2_hat_mat =np.eye(4) 
G2_hat_mat[1:3, 1:3] = G2_hat.T
print(G2_hat_mat)

[[ 1.          0.          0.          0.        ]
 [ 0.          0.99796198  0.06381138  0.        ]
 [ 0.         -0.06381138  0.99796198  0.        ]
 [ 0.          0.          0.          1.        ]]


In [36]:
B4 = G2_hat_mat@B3
B4 = make_zero(B4)
print(B4)

[[ 2.18841694e+01  6.28215995e-02  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  5.13219431e+00  1.21724316e-01 -5.47546550e-02]
 [ 0.00000000e+00  0.00000000e+00  2.23341981e+00 -8.56321604e-01]
 [ 0.00000000e+00 -2.63142383e-03 -1.79715185e-02 -1.30380621e-02]]


In [37]:
G3  = givens_4x4(B4[1][2], B4[1][3])
G3_mat = np.block([[e1,b1],[b1,G3]])
print(G3_mat)

[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          0.91198118  0.41023204]
 [ 0.          0.         -0.41023204  0.91198118]]


In [38]:
B5 = make_zero(B4@G3_mat)
print(B5)

[[ 2.18841694e+01  6.28215995e-02  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  5.13219431e+00  1.33472399e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  2.38812739e+00  1.35271182e-01]
 [ 0.00000000e+00 -2.63142383e-03 -1.10410557e-02 -1.92629600e-02]]


In [39]:
G3_hat = givens_4x4(B5[2][2],B5[3][2])
G3_hat_mat = np.block([[e1,b1],[b1,G3_hat.T]])
print(G3_hat_mat)

[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          0.99998931 -0.00462326]
 [ 0.          0.          0.00462326  0.99998931]]


In [41]:
B6 = make_zero(G3_hat_mat@B5)
print(B6)

In [46]:
def goulab_diag(J):
    A = J

    for _ in range(6):
        t00 = A[0][0]**2
        t33 = A[2][3]**2 + A[3][3]**2
        t10 = A[0][1] * A[0][0]
        
        G0 = givens_4x4((t00-t33),t10)
        b1 = np.zeros((2,2))
        e1 = np.eye(2)
        G0_mat = np.block([[G0,b1],[b1,e1]])
        print(G0_mat)
    
        B1 = A@G0_mat
        print(B1)
    
        G0_hat = givens_4x4(B1[0][0], B1[1][0])
        G0_hat_mat = np.block([[G0_hat.T,b1],[b1,e1]])
        B2 = G0_hat_mat@B1
    
        B2 = make_zero(B2)
        print(B2)
    
        G1 = givens_4x4(B2[0][1],B2[0][2])
        G1_mat = np.eye(4)
        G1_mat[1:3, 1:3] = G1
        print(G1_mat)
    
        B3 = B2@G1_mat
        B3 = make_zero(B3)
        print(B3)
    
        G2_hat = givens_4x4(B3[1][1], B3[2][1])
        G2_hat_mat =np.eye(4) 
        G2_hat_mat[1:3, 1:3] = G2_hat.T
        print(G2_hat_mat)
    
        B4 = G2_hat_mat@B3
        B4 = make_zero(B4)
        print(B4)
    
        G3  = givens_4x4(B4[1][2], B4[1][3])
        G3_mat = np.block([[e1,b1],[b1,G3]])
        print(G3_mat)
    
        B5 = make_zero(B4@G3_mat)
        print(B5)
    
        G3_hat = givens_4x4(B5[2][2],B5[3][2])
        G3_hat_mat = np.block([[e1,b1],[b1,G3_hat.T]])
        print(G3_hat_mat)
    
        B6 = make_zero(G3_hat_mat@B5)
        print(B6)
    
        A = B6



goulab_diag(J)

    
    

[[ 0.52707349  0.84981971  0.          0.        ]
 [-0.84981971  0.52707349  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
[[-21.03695307  -0.16115409   0.           0.        ]
 [  5.90557452  -3.66274367  -3.12752613   0.        ]
 [  0.           0.           2.86689474  -1.45881059]
 [  0.           0.           0.          -0.02235824]]
[[21.85015343 -0.83479572 -0.8452956   0.        ]
 [ 0.          3.56998291  3.01112853  0.        ]
 [ 0.          0.          2.86689474 -1.45881059]
 [ 0.          0.          0.         -0.02235824]]
[[ 1.          0.          0.          0.        ]
 [ 0.         -0.70267393  0.71151201  0.        ]
 [ 0.         -0.71151201 -0.70267393  0.        ]
 [ 0.          0.          0.          1.        ]]
[[21.85015343  1.18802717  0.          0.        ]
 [ 0.         -4.65098805  0.42424421  0.        ]
 [ 0.         -2.03983005 -2.0144922  -1.45881059]
 [ 0.      

In [48]:
A = np.array([
    [1, 2, 3, 4],
    [5, 0, 2, 6],
    [8, 5, 4, 8],
    [6, 9, 7, 9]], dtype=np.float64)

s,v,d = np.linalg.svd(A)
print(v)

[2.18842648e+01 5.13438751e+00 2.39095646e+00 1.86113438e-02]
