In [1]:
import numpy as np
import sys
import math

np.random.seed(0)

def set_lowVal_zero(X):
    low_values_indices = abs(X) < 9e-15   # where values are low
    X[low_values_indices] = 0             # all low values set to 0
    return X

def householder(x, i):
    alpha = -np.sign(x[i])*np.linalg.norm(x)
    print(alpha)
    e = np.zeros(len(x))
    e[i] = 1.0
    v = x - alpha*e
    w = v / np.linalg.norm(v)
    P = np.eye(len(x)) - 2 * np.outer(w, w.T)
    return P
        
A = np.random.randint(10, size=(4,4))
J = A.copy()

for i in range(3):
    
    h = np.zeros(len(A[:,i]))
    h[i:] = J[i: ,i]
    P = householder(h, i)
    J = P@J   
    
    h = np.zeros(len(J[i, :]))
    h[i+1:] = J[i,i+1:]
    Q = householder(h, i+1)
    J = J@Q
    J = set_lowVal_zero(J)
#    with np.printoptions(precision=4, suppress=True, formatter={'float': '{:0.4f}'.format}, linewidth=100):
#        print(J)
    print(J)
    print(' ')



print(J)

-11.916375287812984
15.402807499713793
[[-11.91637529  15.4028075    0.           0.        ]
 [  0.          -3.05418634  -1.59670191  -2.604903  ]
 [  0.          -6.60416932   4.3829604    1.3546433 ]
 [  0.          -1.21313588  -3.42253984  -1.11559849]]
 
7.376639155159193
2.7004829255852942
[[-11.91637529  15.4028075    0.           0.        ]
 [  0.           7.37663916   2.70048293   0.        ]
 [  0.           0.          -3.62848831   3.10168527]
 [  0.           0.           3.5355698   -0.87147871]]
 
5.066180139223167
2.8296669604973186
[[-11.91637529  15.4028075    0.           0.        ]
 [  0.           7.37663916   2.70048293   0.        ]
 [  0.           0.           5.06618014   2.82966696]
 [  0.           0.           0.          -1.54042577]]
 
[[-11.91637529  15.4028075    0.           0.        ]
 [  0.           7.37663916   2.70048293   0.        ]
 [  0.           0.           5.06618014   2.82966696]
 [  0.           0.           0.          -1.54042577

In [2]:
n = 4
m = n-1

print(J[2,2])
print(J[1,2])
print(J[2,3])

for _ in range(3):
    firstMat = np.array([[J[2,2]**2 + J[1,2]**2, J[2,2]*J[2,3]],
                         [J[2,2]*J[2,3],         J[3,3]**2 + J[2,3]**2]
                        ])
    print(firstMat)

    eigenvalues, eigenvectors = np.linalg.eig(firstMat)
    print(eigenvalues)

    ref_val = J[3,3]**2 + J[2,3]**2

    eigen_low = 0;
    min_diff = math.inf;
    for eigen in eigenvalues:
        if abs(eigen-ref_val) < min_diff:
            eigen_low = eigen
            min_diff = abs(eigen-ref_val)

    y = J[0,0]**2 - eigen_low
    x = J[0,0]*J[0,1]

    def givens(i,j,y,x):
        r = np.sqrt(y**2 + x**2)
        c = y/r
        s = x/r

        G = np.eye(4)
        G[i,i] = c
        G[j,j] = c
        G[i,j] = -s
        G[j,i] = -s

        return G

    for k in range(3):
        G = givens(k,k+1,y,x)
        J = J@G

        y = J[k,k]
        x = J[k+1,k]
        
        G = np.transpose(givens(k,k+1,y,x))
        J = G@J

        if k < 2:
            y = J[k,k+1]
            x = J[k,k+2]
            
    print(set_lowVal_zero(J))

5.066180139223166
2.700482925585294
2.8296669604973186
[[32.95878923 14.33560256]
 [14.33560256 10.37992667]]
[39.91657032  3.42214558]
[[-1.0929368   2.00606245  0.          0.        ]
 [ 0.         -1.06928082  1.74040225  0.        ]
 [ 0.          0.          0.5150388  -0.74070948]
 [ 0.          0.          0.         -1.06483935]]
[[ 3.29426494 -0.38149412]
 [-0.38149412  1.68253337]]
[3.38000301 1.5967953 ]
[[ 1.49449241  0.62049185  0.          0.        ]
 [ 0.          0.2407897   0.42673332  0.        ]
 [ 0.          0.         -0.46180764 -0.783252  ]
 [ 0.          0.          0.          0.20623278]]
[[0.39536763 0.36171176]
 [0.36171176 0.65601565]]
[0.14121831 0.91016497]
[[ 0.83530344  0.29319013  0.          0.        ]
 [ 0.          0.16845855 -0.1140292   0.        ]
 [ 0.          0.          0.66688684 -0.57750026]
 [ 0.          0.          0.          0.01992213]]
